### ISSUE TITLE
Autoplay no longer works

### ISSUE THREAD

**Issue by tynatsuhara** [sukumo28/vscode-audio-preview#45] opened 2022-12-16 21:48 UTC
It seems the autoplay feature stopped working in the latest version of VS code (on M1 MacOS at least). I have `"WavPreview.autoPlay": true` in my `settings.json`. When I open an audio file, the "play" button says "stop" (as if it were auto-playing), but I have to click "stop" and then "play" to make it actually play. Tested with wav, ogg, and mp3 files.

VS code installation info:
```
Version: 1.74.1
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:32:34.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```

**Comment by sukumo28** [comment] 2022-12-17 00:14
That's a terrible bug...  
Thank you for sharing.

**Comment by rayandaod** [comment] 2023-03-12 11:28
Same here 👍🏽

**Comment by Jackiexiao** [comment] 2024-01-15 07:24
If you could spare some time to fix this bug, I would be very grateful and happy to offer you a cup of coffee(I mean, sponsor) as a token of appreciation. Thank you so much for your work on the GitHub repository.

**Comment by sukumo28** [comment] 2024-03-06 10:23
This issue was caused by Auto Play Policy.
I'm sorry, but it may not be possible to solve this problem with a general implementation only on the extension side.
This will be resolved if the specifications are changed to avoid Auto Play Policy on the VSCode side, but it is unlikely that such an update will be made.
Therefore, we will close it for now.

reference:
- https://developer.chrome.com/blog/autoplay
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Best_practices#autoplay_policy
- https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

**Closed by sukumo28** 2024-03-06 10:23 UTC
